### PR TITLE
Avoid 4 lines of --- when customization

### PR DESCRIPTION
**Pull request by NicolasCador**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Avoid 4 lines of --- when customization
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Place an order with a product with customization, check alert email received for the new order and there aren't 4 lines of --- at the end of each product with customization

### CODE REVIEW

**Comment by NicolasCador** [comment]
Before:
Before


After:
After

**Comment by NicolasCador** [comment]
hi @mflasquin & @boherm,

ok, done

**Review by boherm — APPROVED** [review]
CI ✅
LGTM, thanks @NicolasCador!

**Review by nicosomb — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @NicolasCador 

Thanks for your PR 🚀 
Indeed without your PR, we use to have these 4 lines of ---:

image

### With your PR ✅ 

image

LGTM, QA ✅ 

Thanks!

**Pull request merged**
