### PR TITLE
Release 2.3.1

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This release contains a number of important bugfixes
| How to test?  | Regular tests of the ps_emailalerts module

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @kpodemski ,

Thanks for this PR !

I am having 2 issues about [#85](https://github.com/PrestaShop/ps_emailalerts/pull/85) and [#95](https://github.com/PrestaShop/ps_emailalerts/pull/95). The 2 bugs are not fixed.

[#85](https://github.com/PrestaShop/ps_emailalerts/pull/85)
I followed [these steps](https://github.com/PrestaShop/PrestaShop/issues/17830#issue-570715296) :
1. Create a product with negative stock and minimal quantity more than 1
2. Subscribe to that product stock as a customer
3. Change stock to 1 (less than minimal quantity)
4. Customer will receive an email saying the product is available but isn't true 🚫 

[#95](https://github.com/PrestaShop/ps_emailalerts/pull/95)
After creating an order from the BO, I have an exception 🚫 
Screenshot 2022-01-21 at 16 43 18

The rest look good :)
Could you check this out ?
Thanks!

**Comment by kpodemski** [comment]
Hello @florine2623 

I've tested the scenario from #85 and cannot reproduce it. Have you tried a product with combinations?

#95 - that's true, I was able to reproduce this error

**Comment by kpodemski** [comment]
@florine2623 

I've just fixed the second issue: https://github.com/PrestaShop/ps_emailalerts/pull/102

**Comment by florine2623** [comment]
Hello @kpodemski ,

For [#85](https://github.com/PrestaShop/ps_emailalerts/pull/85), please check my video : 

https://user-images.githubusercontent.com/16019289/150774459-9ada04ad-3160-4566-8e39-0d1fa550ca0a.mov

I have tested with product combination, the behavior is the same.

Thanks for the new PR [#102](https://github.com/PrestaShop/ps_emailalerts/pull/102) fixing [#95](https://github.com/PrestaShop/ps_emailalerts/pull/95). It is QA ✅ I have updated the PR.

**Comment by kpodemski** [comment]
@florine2623 from what I see, everything is ok, behavior is good, value `3` is for the emails to the merchant informing that there's low quantity of specific product

a better test scenario would be:

1. set product to -10
2. subscribe
3. change minimum quantity to 5
4. now change qty of the product to 4 - you shouldn't receive any email
5. change qty of the product to 5, you should receive an email

**Comment by florine2623** [comment]
Hello @kpodemski ,

Thanks for the update. Indeed, this is not an issue. You are right ^^
After further testing, this release is QA ✅ 

Thanks!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @florine2623

**Pull request merged**
