### PR TITLE
Release 2.3.0

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.3.0. The only meaningful of this change is https://github.com/PrestaShop/ps_emailalerts/pull/81 which fixes major issue https://github.com/PrestaShop/PrestaShop/issues/23743
| How to test?  | Please verify that module behavior is OK (regular test campaign for ps_emailalerts module) and that https://github.com/PrestaShop/PrestaShop/issues/23743 is correctly fixed in the new version

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by aDamelincourt** [comment]
Thanks @matks 
✔️ QA approved

**Comment by aDamelincourt** [comment]
Hello @matks
It's ok on PS1.7.7.3 for ps_emailalerts
But on PS1.7.5.2, I can't finalize my cart, after payment choice, I get a 500 error, in BO, I have got order, but it's empty

**Comment by PierreRambaud** [comment]
> Hello @matks
> It's ok on PS1.7.7.3 for ps_emailalerts
> But on PS1.7.5.2, I can't finalize my cart, after payment choice, I get a 500 error, in BO, I have got order, but it's empty

This module is not compatible with 1.7.5.2, it begins at 1.7.6.0
https://github.com/PrestaShop/ps_emailalerts/blob/dev/ps_emailalerts.php#L79

**Comment by aDamelincourt** [comment]
Thanks @matks 
✔️ QA approved, thanks @PierreRambaud for explanations

**Comment by Progi1984** [comment]
Thanks @matks & @aDamelincourt

**Pull request merged**
