### PR TITLE
Release 2.4.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release version 2.4.2
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

The bump to version 2.4.2 is not available.
Could you check ? ^^

**Comment by Hlavtox** [comment]
@florine2623 Ha, good catch! :D - https://github.com/PrestaShop/ps_emailalerts/pull/136

**Review by leemyongpakvn — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
@Hlavtox ,

The upgrade still won't work. I'm wondering if something is missing in the upgrade folder :
Screenshot 2023-09-01 at 11 13 04

Could you check ? :)

**Comment by Hlavtox** [comment]
@florine2623 Random issue, try to zip the ps_emailalerts folder and install it through BO. :-)

**Review by florine2623 — APPROVED** [review]
The zip option didn't work 😅 

I followed @Hlavtox advice and did this : 
- Uninstall ps_distributionapi
- Clear cache
- Install clean email alerts 2.4.1
- Then try to upgrade the module

Upgrade to 2.4.2 works.

Tested the following :
https://github.com/PrestaShop/ps_emailalerts/pull/121 ✅ 
email alert is sent with correct language regarding shop language :
Screenshot 2023-09-01 at 16 09 57
Screenshot 2023-09-01 at 16 10 04

https://github.com/PrestaShop/ps_emailalerts/pull/127 ✅ 
email is sent when stock a available again

https://github.com/PrestaShop/ps_emailalerts/pull/133
4 lines are not displayed when the order has a customizable product :
Screenshot 2023-09-01 at 16 11 54


It is QA ✅ 
Thanks!

**Comment by leemyongpakvn** [comment]
Thanks @Hlavtox n @florine2623

**Pull request merged**
