### PR TITLE
Correct product name and link if it has attributes

### PR DESCRIPTION
**Pull request by kpodemski**
title says it all

| Sponsor company  | impSolutions

### CODE REVIEW

**Comment by kpodemski** [comment]
ping @eternoendless 

i know that this is a bit annoying for y'all but it would be very cool if someone from the team would look into PR and Issues from Modules from time to time :D

**Comment by eternoendless** [comment]
I know, I know, we have too many repositories to keep track of everything, but you know that already 😉

**Review by eternoendless — APPROVED** [review]
LGTM

**Comment by khouloudbelguith** [comment]
This PR should fix this issue: https://github.com/PrestaShop/PrestaShop/issues/9641

**Comment by marionf** [comment]
@khouloudbelguith This issue is already fixed without this PR
This PR is about customer notifications & product availability option

**Comment by eternoendless** [comment]
Thank you @kpodemski

**Pull request merged**
