### PR TITLE
Change hook name because it's deprecated \o/

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Change hook name because it's deprecated \o/
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed issue | Fixes PrestaShop/PrestaShop#27986 
| How to test?  | No need QA.

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by sLorenzini** [comment]
hello @PierreRambaud,

I can't reproduce the fix because it's impossible to hook the module on any hook available.
When I click on "Transplant a module" button on positions page in Design -> Positions I've got this error :

Capture d’écran 2022-04-04 à 14 38 27

I've also an error when I click on "Manage hooks" button in modules -> ps_emailalerts -> configure page : 

Capture d’écran 2022-04-04 à 14 38 12

The error message in product page has disappeared but I don't have the notify block to add customer email :

Screenshot from 1.7.8.x version
Capture d’écran 2022-04-04 à 14 48 13

Tested on develop branch.

Could you check please?

Thanks

**Comment by PierreRambaud** [comment]
> hello @PierreRambaud,
> 
> I can't reproduce the fix because it's impossible to hook the module on any hook available. When I click on "Transplant a module" button on positions page in Design -> Positions I've got this error :
> 
> Capture d’écran 2022-04-04 à 14 38 27
> 
> I've also an error when I click on "Manage hooks" button in modules -> ps_emailalerts -> configure page :
> 
> Capture d’écran 2022-04-04 à 14 38 12
> 
> The error message in product page has disappeared but I don't have the notify block to add customer email :
> 
> Screenshot from 1.7.8.x version Capture d’écran 2022-04-04 à 14 48 13
> 
> Tested on develop branch.
> 
> Could you check please?
> 
> Thanks

Hi @sLorenzini ,
seems to be related to this issue: https://github.com/PrestaShop/PrestaShop/issues/28074 :D

**Comment by sLorenzini** [comment]
> > hello @PierreRambaud,
> > I can't reproduce the fix because it's impossible to hook the module on any hook available. When I click on "Transplant a module" button on positions page in Design -> Positions I've got this error :
> > Capture d’écran 2022-04-04 à 14 38 27
> > I've also an error when I click on "Manage hooks" button in modules -> ps_emailalerts -> configure page :
> > Capture d’écran 2022-04-04 à 14 38 12
> > The error message in product page has disappeared but I don't have the notify block to add customer email :
> > Screenshot from 1.7.8.x version Capture d’écran 2022-04-04 à 14 48 13
> > Tested on develop branch.
> > Could you check please?
> > Thanks
> 
> Hi @sLorenzini , seems to be related to this issue: [PrestaShop/PrestaShop#28074](https://github.com/PrestaShop/PrestaShop/issues/28074) :D

Indeed thanks :)

**Review by sLorenzini — APPROVED** [review]
Hello @PierreRambaud,

Tested on develop branch and the module can be hooked via: 
- Positions page  in Design -> Positions by clicking on "Transplant a module" button
- on ps_emailalerts -> configure page by clicking on "Manage hooks" button

However, there is a regression on ps_emailalerts module, 2.3.4 version. Issue will be created.

QA ✅  for hook name

Thanks

**Comment by kpodemski** [comment]
Thank you @PierreRambaud @sLorenzini

**Pull request merged**
