### PR TITLE
Prevent compatibility issues with the future version of psgdpr

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fixing a bug in `psgdpr` requires a change here
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Related to https://github.com/PrestaShop/PrestaShop/issues/23312
| How to test?  | Needed for https://github.com/PrestaShop/psgdpr/pull/175
| Sponsor company | impSolutions

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
seems legit

**Review by matthieu-rolland — APPROVED** [review]

**Comment by kpodemski** [comment]
@florine2623 

I merged `psgdpr` already to `develop` :) as you know these two PRs are related

**Review by florine2623 — APPROVED** [review]
Hello @kpodemski ,

Thanks for the PR !

I have tested this PR in conjunction with that one https://github.com/PrestaShop/psgdpr/pull/175.

Tested on 1.7.8.x and develop branch. I used psgdpr v1.4.2 and ps_emailalerts v2.3.4.
There's no more duplication of id gdpr_consent. Now we only have the class element.

I've tested basic feature of ps_emailalerts modules, for customer and merchant notifications.
The reception of the different emails is working well.

So it is QA ✅ for me !

**Comment by kpodemski** [comment]
Thanks @florine2623 🎉

**Pull request merged**
