### PR TITLE
Improve account template

### PR DESCRIPTION
**Pull request by micka-fdz**
Fixes https://github.com/PrestaShop/PrestaShop/issues/17480

### CODE REVIEW

**Comment by micka-fdz** [comment]
Hello, any news?

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-product-team looks like @sam-pires pinged you, what do we require ? It looks like it fix an issue!

By the way, thanks for your contribution @micka-fdz 😄

**Comment by sam-pires** [comment]
hmm 🤔 I don't remember why
I feel like it was because the associated issue is labeled TBS and Waiting for PM.

I am not familiar with this module, but the 3 improvements make sense.


>- Add breadcrumb like on other account pages : Home > Your account
>- Smarty inheritance from customer/page.tpl instead of page.tpl
>- Use {block name='page_title'}...{/block} to insert page title

@NeOMakinG if this one is good to you then we are all good:
>- Smarty inheritance from customer/page.tpl instead of page.tpl

Thanks @micka-fdz !

**Comment by NeOMakinG** [comment]
I think that's fine yes, but I require QA tests anyway

**Comment by Progi1984** [comment]
Thanks @micka-fdz

**Comment by ttoine** [comment]
is it possible to make a release of this module?

**Comment by Progi1984** [comment]
@ttoine Please contact maintainers team on Slack or create an issue. It's not a good way to ask a release in a comment on a closed PR.

**Pull request merged**
