### PR TITLE
Subscribe to out of stock as a guest: fix error insert null into not null column

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix error introduced by https://github.com/PrestaShop/ps_emailalerts/pull/123. Impossible to insert null value in not null column `ps_mailalert_customer_oos.id_customer`.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#32685
| How to test?  | As a guest subscribe to oos notification. You no longer get a error 500

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I'm adding "Waiting for QA" but the issue needs to be validated first, hopefully QA will find a way to validate the issue and then perform the tests.

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @lmeyer1 

The result of the request notification is 200 ok (with PS1789 & PS804), see the attached screenshot below:

image

But the mail is not received :disappointed: 
Please check and feedback.

Thanks!

**Comment by lmeyer1** [comment]
@hibatallahAouadni
Why didn't you receive the email? Did you investigate?
The screenshot does not show if you were logged in or not. The bug happens only if `is_null($id_customer)`. Can you assert that this was true in your tests?

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @lmeyer1 

Please check the attached screen record below:

[pr_129.webm](https://github.com/PrestaShop/ps_emailalerts/assets/23308427/210741cc-97e8-4847-844d-fa7114007c8f)

Waiting for your feedback.

Thanks!

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I encountered the same bug, and as it is not directly related to sending an email feature, I'm mering it as a valid fix. Thank you @lmeyer1

**Comment by kpodemski** [comment]
well, @lmeyer1 I'm not merging it as you targeted the `master` branch :D

**Comment by lmeyer1** [comment]
@kpodemski 
You changed the branch from master to dev. What else is needed to get this PR merged?

**Comment by kpodemski** [comment]
@lmeyer1 we'll have to rebase the PR :/

**Comment by lmeyer1** [comment]
This has already be fixed by https://github.com/PrestaShop/ps_emailalerts/commit/1fc41516b98283acefe458d708fc0a5ac7852490
Thanks @boherm

**Pull request closed without merging**
