### PR TITLE
Fix wordings

### PR DESCRIPTION
**Pull request by lartist**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix wordings
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @lartist

**Comment by jolelievre** [comment]
Hi @l-delin can you approve these changes please?

**Review by okom3pom — APPROVED** [review]

**Comment by l-delin** [comment]
Hello @jolelievre, yes :-) wording ✅

**Comment by l-delin** [comment]
I think this issue can be fixed at the same time? https://github.com/PrestaShop/PrestaShop/issues/31777

Since these strings use the wrong translation domain too. It should be `Modules.Mailalerts.Shop` and not `Modules.Emailalerts.Shop`

**Comment by l-delin** [comment]
The wording is good to go ✅  I just can't add the label

**Review by matthieu-rolland — APPROVED** [review]

**Pull request merged**
