### PR TITLE
php 7.2 compatibility fix

### PR DESCRIPTION
**Pull request by kpodemski**
related to #16

| Sponsor company  | impSolutions

### CODE REVIEW

**Comment by PierreRambaud** [comment]
I want to accept your pull request, but I don't understand why they added a `count` 🤔 If you know why they did it I'm interesting 😄

**Comment by kpodemski** [comment]
@PierreRambaud tbh i don't really know, as you can see $email should be a single email added to $emails array, i think that it was some weird mistake from the beginning

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
So let's go :smile:

**Comment by kpodemski** [comment]
ping @eternoendless merge?

**Comment by matks** [comment]
@kpodemski Not yet, we're waiting for QA team to check this PR solves the issue and does not break another behavior 😉

**Comment by matks** [comment]
Thank you @kpodemski 😄 !

**Pull request merged**
