### PR TITLE
Update notification if no alerts

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Updated notification design https://github.com/PrestaShop/PrestaShop/pull/26806#issuecomment-988661104
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#26806 - do not close
| How to test?  | Open mail alerts section in FO.

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thanks for the PR !

Here's the result I have :
Screenshot 2021-12-22 at 11 46 34
It is different from what there is in the Discount Page, there's is not white margin :
Screenshot 2021-12-22 at 11 44 58

It is the wanted behavior ? 
If yes it will be QA approved. It not, could you check it please ? ^^
Thanks!

**Comment by Hlavtox** [comment]
@florine2623 Hi, just checked. The styling is different because the Mail Alerts page (and other module pages like wishlist) is missing a body class `page-customer-account`, which adds that white background and padding. So, no issue with the template.

It will be done differently in theme-refacto, so I think we should leave it like this. 👍

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
> @florine2623 Hi, just checked. The styling is different because the Mail Alerts page (and other module pages like wishlist) is missing a body class `page-customer-account`, which adds that white background and padding. So, no issue with the template.
> 
> It will be done differently in theme-refacto, so I think we should leave it like this. 👍

Yeah, it looks like it's not related to this PR at all

**Comment by Progi1984** [comment]
Thanks @Hlavtox & @florine2623

**Pull request merged**
