### PR TITLE
Fix backward compatibility for old themes

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Compatibily with old themes
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#27625
| How to test?  |  Module need to work

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
I'd like @kpodemski opinion on this PR because this contribution reverts a change he added in https://github.com/PrestaShop/ps_emailalerts/pull/86

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thanks @matks

It's not that much of the difference thus I'm ok with this change if it helps with BC Breaks.

**Review by matks — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @okom3pom ,

For now, the [issue](https://github.com/PrestaShop/PrestaShop/issues/27625) is not reproduced so I can't test this PR.
We'll wait for the author to add specific steps to reproduce the bug on the issue before testing it !
Thanks!

**Comment by okom3pom** [comment]
You need to have an old theme and use a 1.7.6 < version.

I think the core team will be able to say that the change does not impact the module. It's just to avoid a BC Break

I will try to reproduce but i dont have an old theme

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-maintainers this change is obvious, maybe we could validate it as devs?

**Comment by marsaldev** [comment]
But the minimum version compliancy is 1.7.6, am I missing something? 🤔
https://github.com/PrestaShop/ps_emailalerts/blob/0caaf4b498e708038a69c61b72e79eb770e8d945/ps_emailalerts.php#L80

**Comment by matks** [comment]
@okom3pom People using PrestaShop < 1.7.6 cannot install this module in version 2.3.3 . This PR will be delivered in 2.3.4 or 3.0.0 and it will only be available to stores using PS 1.7.6 or higher.

People with PS 1.7.5 cannot benefit from this PR

**Comment by okom3pom** [comment]
It seems that the problem is also present in 1.7.8.x with an old theme

**Review by kpodemski — APPROVED** [review]

**Comment by matks** [comment]
@okom3pom I see QA team has trouble finding the accurate list of steps to follow to reproduce the issue and then test this PR (see https://github.com/PrestaShop/PrestaShop/issues/27625). Do you think you can jump in?

**Review by matthieu-rolland — APPROVED** [review]

**Comment by lmeyer1** [comment]
@okom3pom Thank you for this fix

**Comment by matks** [comment]
@lmeyer1 In issue https://github.com/PrestaShop/PrestaShop/issues/27625#issuecomment-1098006584 you mentioned it might be out of scope, so in your opinion this PR is not useful?

**Comment by lmeyer1** [comment]
@matks
As @maofree gave me access to his website, I determined that the bug he reported was not due to `ps_emailalerts`, but due to a change of the content of the template variable `$product`. 
I said that the bug report was out of scope, because the source of the problem (even not determined clearly) was neither related to `ps_emailalerts`, nor was it reproducible with PS core.

So yes, if this PR does not fix anything, it might be useless. @okom3pom What do you think? Do you still think its useful or not?

**Comment by okom3pom** [comment]
@lmeyer1   I'm not sure and why id_product is always put to smarty?

**Comment by lmeyer1** [comment]
@okom3pom
As far as I understand, it just doesn't matter if we have `$id_product and $id_product_attribute` or `$product.id_product and $product.id_product_attribute`, they are fully interchangeable. It was the first until 26.8.2021, @kpodemski changed it to the latter.

To answer your question, *why id_product is always put to smarty?*, I think @kpodemski just didn't remove the variable from `$smarty->assign`, when he changed the usage.

**Pull request closed without merging**
