### PR TITLE
Do not stop execution if mail send failed

### PR DESCRIPTION
**Pull request by PierreRambaud**
Catch errors to be sure even if the mail is not working we don't break
the behavior.

### CODE REVIEW

**Comment by matks** [comment]
Thanks @PierreRambaud

**Comment by Anxote** [comment]
Version 2.1.0 worked almost perfect, this version 2.1.1 does not work

**Comment by matks** [comment]
@Anxote can you tell us more ? what does not work for you ?

**Comment by Anxote** [comment]
I do not receive any alerts, no stock, no new orders...

**Comment by PierreRambaud** [comment]
Hey, since we add only a try catch and we can't reproduce your issue. 
Can you provide us more information?
Do you have some logs?
Is there something displayed here: `/admin-dev/configure/advanced/logs/`?
Do you have a module which overrides this module?
Kind regards

**Comment by matks** [comment]
@Anxote are you running php7.2 ?

**Comment by Anxote** [comment]
Good morning, no, I'm working with php 7.1

**Comment by Anxote** [comment]
@PierreRambaud no, I do not have any override with this module, but every day an override of this module is generated automatically, and the whole web stops working, except the backoffice, which works correctly, so that the front oficce works again I have to delete said override, the truth I'm a bit lost with everything, I can not find an explanation. Even when the web works correctly, the module does not send the alerts, neither to the clients nor to me.

**Comment by Anxote** [comment]
This is the file that is generated in the override and everything stops working.

[ps_emailalerts.zip](https://github.com/PrestaShop/ps_emailalerts/files/2848250/ps_emailalerts.zip)

**Comment by PierreRambaud** [comment]
Hum, you said you don't have override but you have a generated override every day..
So I conclude, you have an override :smile:

**Pull request merged**
